version: '3.8'

volumes:
  product_data:

services:

  product_db:
    image: postgres:14
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
  
  app:
    build: ./app/
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - product_db
  
  bot:
    build: ./bot/
    env_file: .env
    depends_on:
      - app
