"""Initial structure

Revision ID: 01
Revises: 
Create Date: 2024-09-01 21:40:28.535795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('current_price', sa.Integer(), nullable=False),
    sa.Column('sum_quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_by_sizes', sa.JSON(), nullable=False),
    sa.Column('nm_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nm_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
